# ./config-template.toml

[model]
    host = "https://nanogpt.com/v1"
    api_key = "key"
    id = "zai-org/glm-5.2:thinking"
    max_tokens = 8192

# web-search tool config. Uses searxng
[web-search]
    # searxng host url
    host_url = "http://localhost:8888"

[message-context]
    uncompressed_messages = 20

[workspace]
    # Temporary agent run workspace. Do not comment next line.
    # temporary_workspace = "/temp"
    # 
    # Permanent agent workspace. Do not comment next line.
    # permanent_workspace = "/perm"